import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google"; // Import Roboto dari next/font/google
import "./globals.scss"; // Gunakan file global SCSS (tanpa "module")
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto", // Tambahkan custom variable untuk Roboto
  weight: ["400", "700"], // Gunakan variasi berat yang diinginkan
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}
      >
        {children}
        {modal}
      </body>
    </html>
  );
}
